from __future__ import annotations

import re
from dataclasses import dataclass, asdict

from .compiler import compile_scene, _safe_text_action


@dataclass
class Candidate:
    name: str
    prompt: str
    token_estimate: int
    negative_count: int
    hard_constraint_coverage: int
    score: float = 0.0

    def to_dict(self):
        return asdict(self)


def _token_estimate(text: str) -> int:
    return max(1, round(len(text) / 4))


def _negative_count(text: str) -> int:
    return len(re.findall(r"\b(?:no|not|never|without|avoid|don't|do not|must not)\b", text, re.I))


def _contract(scene: dict) -> list[str]:
    rules = scene.get("rules", {}) or {}
    lines = ["OUTPUT CONTRACT:"]
    if scene.get("text_whitelist"):
        lines.append("Visible text is restricted to the exact whitelist above; render no additional words or subtitles.")
    if scene.get("screen_text"):
        lines.append("Treat each exact string as a separate static state; use hard cuts between states and never morph or scramble letters.")
    if rules.get("no_arabic_on_screen"):
        lines.append("Arabic is audio-only; Arabic writing is added later in editing.")
    if rules.get("no_auto_subtitles"):
        lines.append("Automatic subtitles are disabled.")
    if rules.get("no_background_music"):
        lines.append("Background music is disabled.")
    if rules.get("presenter_arabic_only"):
        lines.append("Presenter voice is Egyptian Arabic only; German pronunciation is not generated by the presenter.")
    if rules.get("same_presenter"):
        lines.append("Preserve the same presenter identity, wardrobe, studio and lighting.")
    return lines if len(lines) > 1 else []


def _safe_events(scene: dict) -> list[dict]:
    screen_text = scene.get("screen_text", []) or []
    out = []
    for event in scene.get("timeline", []) or []:
        action = str(event.get("action", ""))
        if screen_text:
            action = _safe_text_action(action)
        out.append({**event, "action": action})
    return out


def _minimal(scene: dict) -> str:
    parts = [f"{scene.get('aspect_ratio', '9:16')} video, exactly {scene.get('duration_seconds', 10)}s."]
    if scene.get("style"):
        parts.append("Style: " + "; ".join(map(str, scene["style"])) + ".")
    spoken = (scene.get("spoken") or {}).get("arabic")
    if spoken:
        parts.append(f'Arabic dialogue: "{spoken}"')
    if scene.get("screen_text"):
        parts.append("Exact screen text: " + " | ".join(map(str, scene["screen_text"])) + ".")
    events = _safe_events(scene)
    if events:
        parts.append("Ordered beats: " + "; ".join(str(e.get("action", "")) for e in events) + ".")
    parts.extend(_contract(scene))
    return "\n".join(parts)


def _timeline_first(scene: dict) -> str:
    lines = [f"SHOT: {scene.get('aspect_ratio', '9:16')}, exact {scene.get('duration_seconds', 10)}s."]
    if scene.get("style"):
        lines.append("Style: " + "; ".join(map(str, scene["style"])) + ".")
    cursor = 0.0
    for e in _safe_events(scene):
        sec = float(e.get("seconds", 0) or 0)
        lines.append(f"{cursor:g}-{cursor+sec:g}s: {e.get('action', '').strip()}")
        cursor += sec
    if scene.get("screen_text"):
        lines.append("Exact visible strings only: " + " | ".join(map(str, scene["screen_text"])))
    spoken = (scene.get("spoken") or {}).get("arabic")
    if spoken:
        lines.append(f'Arabic speech only: "{spoken}"')
    lines.extend(_contract(scene))
    return "\n".join(lines)


def _coverage(scene: dict, prompt: str) -> int:
    required = []
    rules = scene.get("rules", {}) or {}
    if scene.get("text_whitelist"):
        required.extend(map(str, scene.get("text_whitelist", [])))
    if rules.get("no_arabic_on_screen"):
        required.append("Arabic")
    if rules.get("no_auto_subtitles"):
        required.append("subtitles")
    if rules.get("no_background_music"):
        required.append("music")
    if rules.get("presenter_arabic_only"):
        required.extend(["Egyptian Arabic", "German"])
    if rules.get("same_presenter"):
        required.append("presenter")
    if not required:
        return 100
    found = sum(1 for item in required if item.lower() in prompt.lower())
    return round(found / len(required) * 100)


def build_candidates(scene: dict, provider: str = "generic") -> list[Candidate]:
    prompts = [
        ("A · strict compiler", compile_scene(scene)),
        ("B · minimal intent", _minimal(scene)),
        ("C · timeline first", _timeline_first(scene)),
    ]
    out: list[Candidate] = []
    for name, prompt in prompts:
        neg = _negative_count(prompt)
        tok = _token_estimate(prompt)
        coverage = _coverage(scene, prompt)
        score = 100.0 - min(25, tok / 30) - min(20, neg * (3 if provider == "runway" else 1))
        score -= (100 - coverage) * 0.8
        if name.startswith("C") and scene.get("timeline"):
            score += 5
        if name.startswith("A") and (scene.get("rules") or {}).get("no_arabic_on_screen"):
            score += 4
        if name.startswith("A") and any(
            re.search(r"\b(?:transform|morph|animate)\b[^\n.;]{0,120}\b(?:into|to)\b", str(e.get("action", "")), re.I)
            for e in scene.get("timeline", []) or [] if isinstance(e, dict)
        ):
            score += 10
        out.append(Candidate(name, prompt, tok, neg, coverage, round(score, 2)))
    return sorted(out, key=lambda c: c.score, reverse=True)
